# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DevOps Library
email: admin@devopslibrary.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the DevOps Library!  Free full video courses and tutorials on everything DevOps!  We cover everything from Jenkins, to Salt, Puppet, PowerShell and more!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.devopslibrary.com" # the base hostname & protocol for your site
twitter_username: devopslibrary
github_username:  kenerwin88
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
safe: true

# Outputting
permalink: none

whitelist:
  - jekyll-sitemap
